# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - pdf
  - epub

python:
  # Mininum supported Python version
  version: "3.6"
  # NB: install . first to avoid upgrading past docs/requirements.txt pins
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
